# -*- coding: utf-8 -*-
"""Submission Dicoding Deep Learning Akhir_MobileNetV2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWOdLQHnQnRVHBG0Dmt8dLQxNsOL6dpC

# Proyek Klasifikasi Gambar: Fruits and Vegetables Dataset
- **Nama:** Nabila Putri Asy Syifa
- **Email:** nabilaputriasysyifa99@gmail.com

Dataset yang digunakan merupakan dataset gambar buah dan sayuran yang terdiri dari **20 kelas** berdasarkan jenis dan kondisinya (segar dan busuk), yaitu **Fresh Apple, Fresh Banana, Fresh Mango, Fresh Orange, Fresh Strawberry, Rotten Apple, Rotten Banana, Rotten Mango, Rotten Orange, Rotten Strawberry, Fresh Bell Pepper, Fresh Carrot, Fresh Cucumber, Fresh Potato, Fresh Tomato, Rotten Bell Pepper, Rotten Carrot, Rotten Cucumber, Rotten Potato, dan Rotten Tomato**.

Dimana dataset ini diperoleh dari **[Kaggle](https://kaggle.com)** melalui tautan berikut ini:**[Fruits and Vegetables Dataset](https://www.kaggle.com/datasets/muhriddinmuxiddinov/fruits-and-vegetables-dataset)**.

Dataset ini berjumlah total sebanyak **12.000 gambar** (terdiri dari **5.997** gambar kategori buah dan **6.003** gambar kategori sayur), dan di setiap kelasnya rata-rata didistribusikan secara seimbang sebanyak **±600** gambar.

## Import Semua Packages/Library yang Digunakan
"""

# Install library splitfolders dan tensorflowjs
!pip install split-folders tensorflowjs

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import os, shutil, random, zipfile, splitfolders

# Import library untuk pemodelan neural network
import tensorflow as tf
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Dense, Flatten, Dropout, Conv2D, MaxPooling2D, BatchNormalization, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

# Abaikan warnings
import warnings
warnings.filterwarnings('ignore')

"""## Data Preparation

### Data Loading
"""

# Upload token API akun kaggle
from google.colab import files
files.upload()

# Load dataset dari kaggle "Fruits and Vegetables Dataset"
# Membuat direktori .kaggle
!mkdir -p ~/.kaggle

# Salin file kaggle.json ke direktori .kaggle
!cp kaggle.json ~/.kaggle/

# Izin untuk file kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

# Download dataset dari Kaggle
print("Mengunduh dataset Fruits and Vegetables...\n")
!kaggle datasets download -d muhriddinmuxiddinov/fruits-and-vegetables-dataset

# Ekstrak dataset dari file ZIP
print("\nMengekstrak file zip Fruits & Vegetables...")
local_zip = 'fruits-and-vegetables-dataset.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')

# Ekstrak ke folder spesifik di dalam "tmp" agar tidak tercampur
zip_ref.extractall('/tmp')
zip_ref.close()
print("Ekstraksi selesai! Dataset berada di folder: /tmp/Fruits_Vegetables_Dataset")

"""### Data Preprocessing

#### Split Dataset
"""

# Lokasi utama tempat file ZIP dataset diekstrak sebelumnya
extracted_dir = '/tmp'

# Buat folder Gabungan untuk menyatukan kelas buah dan sayur
base_dir = '/tmp/Fruits_Vegetables_Merged'
os.makedirs(base_dir, exist_ok=True)

print("Mencari lokasi pasti folder Fruits dan Vegetables...")

# Gunakan os.walk untuk menelusuri seluruh subfolder di dalam /tmp secara otomatis
for root, dirs, files in os.walk(extracted_dir):
    for cat in dirs:
        # Cari folder yang bernama "Fruits" atau "Vegetables"
        if cat.lower() in ['fruits', 'vegetables']:
            cat_path = os.path.join(root, cat)
            print(f" Ditemukan folder target di: {cat_path}")

            # Pindahkan isi subfoldernya ke folder Merged
            for class_name in os.listdir(cat_path):
                src_path = os.path.join(cat_path, class_name)
                dst_path = os.path.join(base_dir, class_name)

                if os.path.isdir(src_path) and not os.path.exists(dst_path):
                    shutil.copytree(src_path, dst_path)

# Cek jumlah kelas yang berhasil dikumpulkan
jumlah_kelas = len(os.listdir(base_dir))
print(f"\nBerhasil mengumpulkan {jumlah_kelas} kelas ke folder: {base_dir}")

# Folder output untuk hasil split data
output_dir = '/tmp/Fruits_Veg_Image_Split'

# Split data ke dalam Train, Val, dan Test dengan rasio 80:10:10
if jumlah_kelas > 0:
    print("Memulai pembagian dataset dengan rasio 80:10:10...")
    splitfolders.ratio(base_dir, output=output_dir, seed=42, ratio=(.8, .1, .1))
    print("\nPembagian selesai!")
    print(f"Dataset siap digunakan di folder: {output_dir}")
else:
    print("\n GAGAL: Folder dataset tetap tidak ditemukan.")
    print("Mari kita intip isi dari folder /tmp untuk melihat nama aslinya:")
    print(os.listdir('/tmp'))

# Distribusi kelas pada data latih (Fruits & Vegetables)
train_dir = os.path.join(output_dir, 'train')
val_dir = os.path.join(output_dir, 'val')
test_dir = os.path.join(output_dir, 'test')

# Menghitung jumlah kelas berdasarkan jumlah sub-folder di direktori train
num_classes = len(os.listdir(train_dir))
print(f"Jumlah kelas data latih: {num_classes}")

"""#### Preview Dataset"""

# Variabel untuk menyimpan gambar beserta label atau kelasnya
all_sample_images = []
all_sample_labels = []

# Definisikan ukuran gambar sesuai standar MobileNetV2
IMG_SIZE = (224, 224)

# Ambil 5 sampel gambar pada setiap kelas
for class_name in sorted(os.listdir(train_dir)): # Tambahan 'sorted' agar urut abjad
    class_dir = os.path.join(train_dir, class_name)

    # Lewati jika bukan folder (misal ada file tersembunyi)
    if not os.path.isdir(class_dir):
        continue

    # Load 5 sampel gambar pada setiap kelas
    for i, image_file in enumerate(os.listdir(class_dir)):
        if i >= 5:
            break
        image_path = os.path.join(class_dir, image_file)
        img = Image.open(image_path).convert('RGB') # Pastikan format warna RGB
        img = img.resize(IMG_SIZE)
        all_sample_images.append(np.array(img))
        all_sample_labels.append(class_name)

# Konfigurasi ukuran grid layout
num_classes = len(os.listdir(train_dir))
images_per_class = 5

# Hitung ukuran grid untuk visualisasi
row_size = num_classes
col_size = images_per_class

# Visualisasi dengan subplots
fig, axes = plt.subplots(row_size, col_size, figsize=(col_size * 3, row_size * 3))
axes = axes.flatten()

# Plot gambar di setiap grid berdasarkan kelasnya
for i, (img_array, label) in enumerate(zip(all_sample_images, all_sample_labels)):
    ax = axes[i]
    ax.imshow(img_array)
    ax.set_title(f'{label} ({i % images_per_class + 1})', fontsize=12)
    ax.axis('off')

# Jika terdapat subplots yang tidak digunakan, hapus subplots nya
for i in range(len(all_sample_images), row_size * col_size):
    fig.delaxes(axes[i])

plt.tight_layout(h_pad=1.5)
plt.show()

# Fungsi untuk mengecek jumlah gambar dan ukuran resolusi
def print_images_resolution(directory):
    unique_sizes = set()
    total_images = 0

    # Tambahan sorted() agar nama kelas berurutan sesuai abjad
    for subdir in sorted(os.listdir(directory)):
        subdir_path = os.path.join(directory, subdir)

        # Pengamanan: Lewati jika item tersebut bukan sebuah folder
        if not os.path.isdir(subdir_path):
            continue

        image_files = os.listdir(subdir_path)
        num_images = len(image_files)
        print(f"Jumlah gambar pada kelas '{subdir}': {num_images}")
        total_images += num_images

        # Hanya 5 gambar yang dilihat resolusinya
        for i, img_file in enumerate(image_files):
            if i >= 5:
                break
            img_path = os.path.join(subdir_path, img_file)

            # Gunakan try-except untuk berjaga-jaga jika ada file gambar korup dari dataset Kaggle
            try:
                with Image.open(img_path) as img:
                    unique_sizes.add(img.size)
            except Exception:
                continue

        print(f"Resolusi pada gambar sampel sebanyak 5 data:")
        for size in unique_sizes:
            print(f"- {size}")
        print("------------------------------")
        unique_sizes.clear()

    print(f"\nTotal gambar pada seluruh kelas dalam direktori ini: {total_images}")

# Menerapkan panggilan fungsi pengecekan gambar
print_images_resolution(train_dir)

"""#### Image Data Augmetation"""

# Augmentasi data gambar dengan image data generator (untuk dataset Buah & Sayur)
train_datagen = ImageDataGenerator(
    rescale=1./255,               # Normalisasi piksel dari [0, 255] ke [0, 1]
    rotation_range=40,            # Rentang rotasi acak (derajat) Buah bisa miring ke segala arah
    width_shift_range=0.2,        # Geser horizontal acak
    height_shift_range=0.2,       # Geser vertikal acak
    shear_range=0.2,              # Perubahan bentuk (shear) acak
    zoom_range=0.2,               # Zoom acak
    brightness_range=[0.8, 1.2],  # Kecerahan pada gambar
    horizontal_flip=True,         # Balik horizontal acak
    # vertical_flip=True,         # Untuk dibalik atas-bawah
    fill_mode='nearest'           # Pengisian piksel yang hilang setelah transformasi
)

val_datagen = ImageDataGenerator(rescale=1./255)

# Load dataset gambar Fruits & Vegetables dari direktori untuk augmentasi data
IMG_SIZE = (224, 224) # Standar ukuran input untuk MobileNetV2
BATCH_SIZE = 32

print("Memuat Data Training...")
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

print("\nMemuat Data Validation...")
val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print("\nMemuat Data Testing...")
test_generator = val_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

# Mapping kelas pada dataset Fruits and Vegetables
print(train_generator.class_indices)

# Inspeksi dataset gambar hasil augmentasi (Fruits & Vegetables) dengan matplotlib
def plot_images(images_arr):
    fig, axes = plt.subplots(1, 5, figsize=(20, 20))
    axes = axes.flatten()
    for img, ax in zip(images_arr, axes):
        ax.imshow(img)
    plt.tight_layout()
    plt.show()

# Cek plot dataset gambar hasil augmentasi (Fruits & Vegetables)
imgs, labels = next(train_generator)
plot_images(imgs[:5])

"""## Modeling"""

# Variabel global untuk parameter arsitektur model
input_shape = (224, 224, 3)

# Dapatkan jumlah kelas
num_classes = len(train_generator.class_indices)

# Load Base Model MobileNetV2
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=input_shape
)

# Proses Fine-Tuning
base_model.trainable = True
fine_tune_at = 100
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

# Arsitektur model sequential
model = Sequential()
model.add(base_model)
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))

model.add(GlobalAveragePooling2D())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

print("Arsitektur Fine-Tuned MobileNetV2 dengan Conv2D berhasil dibangun!")

# Kompilasi model MobileNetV2 yang termasuk model CNN Deep Learning
model.compile(optimizer=Adam(learning_rate=0.00001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Menampilkan ringkasan arsitektur model MobileNetV2
model.summary()

# Dapatkan label dari generator Fruits & Vegetables
class_labels = train_generator.classes

# Hitung bobot untuk mengatasi sedikit ketidakseimbangan data
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(class_labels),
    y=class_labels
)

# Ubah menjadi format dictionary agar bisa dibaca oleh model.fit
class_weights_dict = dict(enumerate(class_weights))

print("\nClass Weights yang akan digunakan untuk 20 kelas:")
print(class_weights_dict)

# Latih model CNN Deep Learning
EPOCHS = 50

print('\nMemulai pelatihan model MobileNetV2...')

# Custom Callback untuk stop training jika nilai akurasi sudah optimal (≥ 95%)
class TargetAccuracy(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy') >= 0.95 and logs.get('val_accuracy') >= 0.95):
            print("\nTarget akurasi 95% pada Train dan Val tercapai! Menghentikan training...")
            self.model.stop_training = True

target_callback = TargetAccuracy()

# Callback standar: Berhenti jika loss validasi tidak membaik selama 5 epoch
early_stop = EarlyStopping(monitor='val_loss',
                           patience=5,
                           restore_best_weights=True)

# Simpan model
model_checkpoint = ModelCheckpoint('mobilenetv2_fruits_veg_best.keras',
                                   monitor='val_accuracy',
                                   save_best_only=True,
                                   mode='max')

# Optimalisasi learning rate agar titik optimal bobot tercapai
reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                              factor=0.2,
                              patience=3,
                              min_lr=0.00001) # Batas minimum

# Pelatihan model
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=val_generator,
    validation_steps=val_generator.samples // BATCH_SIZE,
    callbacks=[early_stop, model_checkpoint, target_callback, reduce_lr],
    class_weight=class_weights_dict
)

"""## Evaluasi dan Visualisasi"""

# Evaluasi model MobileNetV2 dengan data uji (test) Fruits & Vegetables
test_loss, test_acc = model.evaluate(test_generator)
print(f"Test accuracy MobileNetV2: {test_acc:.4f}, Test loss: {test_loss:.4f}")

# Plot hasil train model MobileNetV2 dari history
def plot_history(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']

    epochs_range = range(len(acc))

    # Plot hasil akurasi Training dan Validation
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy')
    plt.plot(epochs_range, val_acc, label='Validation Accuracy')
    plt.legend(loc='lower right')
    plt.title('Training & Validation Accuracy (MobileNetV2)')

    # Plot hasil loss Training and Validation
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, label='Training Loss')
    plt.plot(epochs_range, val_loss, label='Validation Loss')
    plt.legend(loc='upper right')
    plt.title('Training & Validation Loss (MobileNetV2)')

    plt.tight_layout()
    plt.show()

# Terapkan fungsi plot untuk melihat grafik hasil training MobileNetV2
plot_history(history)

"""## Konversi Model"""

# Load model MobileNetV2 terbaik yang telah dilatih
best_model = tf.keras.models.load_model('mobilenetv2_fruits_veg_best.keras')

"""#### Saved Model"""

# Buat folder spesifik untuk menyimpan model MobileNetV2 terbaik
export_dir = 'saved_model'

# Simpan model terbaik ke dalam folder dengan format standar TensorFlow
best_model.export(export_dir)

print(f"Model berhasil diekspor ke folder: {export_dir}")

"""#### TensorFlow.js Model"""

# Import library tfjs untuk simpan model format tfjs
import tensorflowjs as tfjs

# Buat folder spesifik untuk menyimpan format TFJS Buah & Sayur
tfjs_dir = "tfjs_model"
os.makedirs(tfjs_dir, exist_ok=True)

# Konversi dari model TensorFlow (best_model) ke format TFJS
print("Memulai konversi model ke format TensorFlow.js...")
tfjs.converters.save_keras_model(best_model, tfjs_dir)

print(f"Konversi selesai! Model TFJS siap diunduh di folder: {tfjs_dir}")

"""#### Tensor Flow-LITE Model"""

# Konversi model MobileNetV2 ke format TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(best_model)
tflite_model = converter.convert()

# Simpan hasil konversi
tflite_filename = "model.tflite"

with open(tflite_filename, "wb") as f:
    f.write(tflite_model)

print(f"Konversi TFLite selesai! Model disimpan sebagai: {tflite_filename}")

# Ambil daftar nama kelas/label dari generator
labels = list(train_generator.class_indices.keys())

# Simpan label ke dalam file .txt
label_filename = "label.txt"

with open(label_filename, "w") as f:
    f.write("\n".join(labels))

print(f"Berhasil menyimpan {len(labels)} label ke dalam file: {label_filename}")

"""## Inference (Optional)"""

# Import library Colab untuk mengunggah file gambar
from google.colab import files

# Uji coba dengan data gambar hewan di luar lingkup model
# Tentukan path ke SavedModel Buah dan Sayur
saved_model_path = 'saved_model'

# Muat SavedModel
print(f"Memuat SavedModel MobileNetV2 dari: {saved_model_path}")
loaded_model = tf.saved_model.load(saved_model_path)

# Dapatkan fungsi inference dari SavedModel 'serving_default'
infer = loaded_model.signatures["serving_default"]
print("SavedModel berhasil dimuat dan siap digunakan!")

# Siapkan contoh gambar untuk inference
# Upload gambar dari komputer lokal
print("\nSilakan unggah gambar buah atau sayur yang ingin diuji:")
uploaded = files.upload()

if uploaded:
    # Dapatkan nama file gambar yang diunggah
    uploaded_image_name = list(uploaded.keys())[0]

    # Path file relatif di Colab
    sample_image_path = uploaded_image_name

    print(f"\nMenggunakan gambar: {uploaded_image_name}")

    # Muat dan proses gambar sesuai standar MobileNetV2
    img = Image.open(sample_image_path).convert('RGB')
    IMG_SIZE = (224, 224)
    img_resized = img.resize(IMG_SIZE)
    img_array = np.array(img_resized).astype(np.float32)
    img_array = np.expand_dims(img_array, axis=0)

    # Normalisasi piksel
    if np.max(img_array) > 1.0:
        img_array /= 255.0

    # Lakukan prediksi
    print("Menganalisis gambar...")
    predictions = infer(tf.constant(img_array))

    # Cari kunci output dari kamus predictions
    output_key = list(predictions.keys())[0]
    predictions_tensor = predictions[output_key]

    # Dapatkan indeks kelas prediksi
    predicted_class_index = np.argmax(predictions_tensor.numpy(), axis=1)[0]
    confidence = np.max(predictions_tensor.numpy(), axis=1)[0]

    # Dapatkan mapping class_indices dari train_generator untuk mendapatkan nama kelas
    if 'train_generator' in globals():
        class_indices = train_generator.class_indices
        idx_to_class = {v: k for k, v in class_indices.items()}
        predicted_class_name = idx_to_class[predicted_class_index]
    else:
        # Alternatif jika train_generator terhapus
        print("\n 'train_generator' tidak ditemukan di memori.")
        predicted_class_name = f"Kelas ke-{predicted_class_index}"

    # Tampilkan hasil
    print(f"\n HASIL PREDIKSI ")
    print(f"Gambar ini terdeteksi sebagai : {predicted_class_name.upper()}")
    print(f"Tingkat Kepercayaan Model     : {confidence * 100:.2f}%\n")

    # Visualisasikan gambar yang diunggah
    plt.figure(figsize=(5, 5))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Prediksi: {predicted_class_name.upper()} ({confidence*100:.1f}%)", fontsize=14, fontweight='bold')
    plt.show()

else:
    print("\n Tidak ada gambar yang diunggah. Silakan jalankan ulang cell ini.")